### ISSUE TITLE
`pgdata/.gitignore: Permission denied` when running `git status`

### ISSUE THREAD

**Issue by nicomihalich** [hannaj06/fleet_watch#10]
Do we need that directory or can we fix the permissions on it?

**Comment by hannaj06** [comment]
So we need that directory for the postgres data, otherwise the data wouldn't persist when you close and reopen the docker container.  I think docker by default changes the permissions for all the files in that directory.

We could just remove it but you can't commit an empty folder to github as far as I'm aware.

**Comment by hannaj06** [comment]
try the new branch, `pgdata_perm` I think that should do it
